{
 "title": "Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Allocs Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(envoy_server_uptime{job=\"api-deployment\"})"
    }
   ]
  },
  {
   "title": "Payments Primary Allocs Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(envoy_server_uptime{job=\"payments-primary\"})"
    }
   ]
  },
  {
   "title": "Payments Canary Allocs Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(envoy_server_uptime{job=\"payments-deployment\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(envoy_server_uptime{job=\"api-deployment\"})",
     "legendFormat": "API Pods"
    },
    {
     "expr": "count(envoy_server_uptime{job=\"payments-deployment\"})",
     "legendFormat": "Payments Canary Pods"
    },
    {
     "expr": "count(envoy_server_uptime{job=\"payments-primary\"})",
     "legendFormat": "Payments Primary Pods"
    }
   ]
  },
  {
   "title": "Downstream error count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_http_downstream_rq_xx{consul_source_service=\"ingress\", envoy_response_code_class=\"5\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "Retries per Second",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_cluster_upstream_rq_retry{consul_destination_service=\"payments\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "Payments Outlier Ejection",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{consul_destination_service=\"payments\"})"
    }
   ]
  },
  {
   "title": "API Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{consul_source_service=\"ingress\", envoy_response_code_class=~\"2|5\"}[60s])) by (envoy_response_code_class)",
     "legendFormat": "Downstream Response Code {{envoy_response_code_class}}xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq{consul_source_service=\"api\",consul_destination_service=\"payments\"}[$__rate_interval])) by (envoy_response_code)",
     "legendFormat": "Payments Upstream Response Code {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Payments Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{local_cluster=\"payments\", job=~\"payments-deployment\"}[$__rate_interval]))",
     "legendFormat": "Canary - {{envoy_response_code}}"
    },
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{job=~\"payments-primary\",local_cluster=\"payments\"}[$__rate_interval]))",
     "legendFormat": "Primary - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Latency - API",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Latency - Payments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"payments\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"payments\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_service=\"payments\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "{app=\"api\"}"
    }
   ]
  },
  {
   "title": "Payments Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{app=~\"payments.*\"}"
    }
   ]
  }
 ]
}